---

- name: Base Gnome state
  set_fact:
    gnome_installed: false

- name: Check Gnome is installed
  set_fact: 
    gnome_installed: true
  when: lookup('env','GDMSESSION') == 'gnome-shell'

- name: Ubuntu | Install Gnome extensions
  apt:
    name: "{{ extensions}}"
    state: present
  when:
    - ansible_distribution == "Ubuntu"
    - gnome_installed
    - extensions is defined
  become: yes

- name: Fedora | Install Gnome extensions
  dnf:
    name: "{{ extensions}}"
    state: present
  when:
    - ansible_distribution == "Fedora"
    - gnome_installed
    - extensions is defined
  become: yes
