---

- name: Base Gnome state
  set_fact:
    gnome_installed: false

- name: Check Gnome is installed
  set_fact:
    gnome_installed: true
  when: lookup('env','GDMSESSION') in ['gnome-shell', 'pop']

- name: Ubuntu | Install Gnome extensions
  apt:
    name: "{{ (ansible_distribution_version == '19.10') | ternary(ubuntu_eoan_gnome_extensions, ubuntu_gnome_extensions) }}"
    state: present
  when:
    - ansible_distribution == "Ubuntu"
    - gnome_installed
  become: yes

- name: Fedora | Install Gnome extensions
  dnf:
    name: "{{ fedora_gnome_extensions}}"
    state: present
  when:
    - ansible_distribution == "Fedora"
    - gnome_installed
  become: yes
