---
- name: Check Snap is installed
  apt:
    name: snapd
    state: present
  become: yes

- name: Check installed Snap packages
  command: snap list
  register: snap_list_output

- set_fact:
    installed_snap_packages: []

- name: Build installed Snap packages list
  set_fact:
    installed_snap_packages: "{{ installed_snap_packages + [item.split(' ')[0]] }}"
  with_items: "{{ snap_list_output.stdout_lines }}"

- name: Install Snap packages
  command: "snap install {{ item.name }}"
  when:
    - snap_apps is defined
    - "item.name | string not in installed_snap_packages"
    - "not item.classic"
  with_items: "{{ snap_packages }}"
  become: yes

- name: Install classic confinement Snap packages
  command: "snap install {{ item.name }} --classic"
  when:
    - snap_apps is defined
    - "item.name | string not in installed_snap_packages"
    - "item.classic"
  with_items: "{{ snap_packages }}"
  become: yes
