---

- name: Install rpmfusion repos
  dnf:
    name: "{{ rpm_fusion_repos }}"
    state: present
  become: yes

- name: Install required packages
  dnf:
    name: "{{ required_packages }}"
    state: latest
  when: required_packages is defined
  become: yes

- name: remove yum email apps
  dnf:
    name: "{{ email_packages }}"
    state: absent
  become: yes

- name: Remove libreoffice
  dnf:
    name: libreoffice*
    state: absent
    autoremove: yes
  become: yes
  ignore_errors: yes

- name: Check if PostgreSQL database is initialized.
  stat:
    path: "{{ postgresql_data_dir }}/PG_VERSION"
  register: pgdata_dir_version
  become: true
