---
- name: Set up a local Ubuntu machine
  connection: local
  hosts: 127.0.0.1
  vars:
    apt_package_list:
      - git
      - geary
      - build-essential
      - meld
      - cheese
      - curl
      - python3-distutils
      - apt-transport-https
      - ca-certificates
      - postgresql
      - zsh
      - vim
      - fonts-powerline
      - fonts-firacode
      - keepassxc
      - tilix
      - tlp
      - nautilus-dropbox
      - python3

    snap_package_list:
      - { name: bitwarden, classic: False }
      - { name: libreoffice, classic: False }
      - { name: pycharm-professional, classic: True }
      - { name: remmina, classic: False }
      - { name: spotify, classic: False }
      - { name: sublime-text, classic: True }
      - { name: heroku, classic: True }

  roles:
    - { name: base_system_tasks, apt_packages: "{{ apt_package_list }}" }
    - vscode
    - chrome
    - powershell_core
    - dotnet_core_sdk
    - docker
    - { name: snap_apps, snap_apps: "{{ snap_package_list }}" }
    - node
