---
- name: Set up a local Ubuntu machine
  connection: local
  hosts: 127.0.0.1
  vars:
    apt_packages:
      - git
      - geary
      - build-essential
      - meld
      - cheese
      - curl
      - python3-distutils
      - apt-transport-https
      - ca-certificates
      - postgresql
      - zsh
      - vim
      - fonts-powerline
      - fonts-firacode
      - keepassxc
      - tilix
      - tlp
    snap_packages:
      - { name: bitwarden, classic: False }
      - { name: libreoffice, classic: False }
      - { name: pycharm-professional, classic: True }
      - { name: remmina, classic: False }
      - { name: spotify, classic: False }
      - { name: sublime-text, classic: True}

  roles:
    - powershell_core
    - dotnet_core_sdk
    - docker
    - {name: snap_apps, snap_apps: "{{ snap_packages }}"}
    - node

  tasks:
    - name: kill elementary appcenter
      command: pkill -f io.elementary.appcenter
      ignore_errors: yes

    - name: update and upgrade system packages
      apt:
        update_cache: yes
        upgrade: full
      become: yes

    - name: install required packages
      apt:
        name: "{{ apt_packages }}"
        state: latest
        autoremove: yes
      become: yes

    - name: remove thunderbird
      apt:
        name: thunderbird
        state: absent
      become: yes

    - name: Remove apt libreoffice
      apt:
        name: libreoffice*
        state: absent
        autoremove: yes
        purge: yes

    - name: get my zsh theme
    get_url:
      url: "https://raw.githubusercontent.com/Toyonut/zsh-theme/master/paul.zsh-theme"
      dest: ~/.oh-my-zsh/themes/paul.zsh-theme


