---
- name: Set up a local machine
  connection: local
  hosts: 127.0.0.1
  pre_tasks:
    - name: Use snap install of dotnet
      set_fact:
        snap_dotnet_install: no
    - name: install pgadmin4
      set_fact:
        install_pgadmin: no

  vars:
    apt_package_list:
      - smartmontools
      - git
      - build-essential
      - cheese
      - curl
      - python3-distutils
      - apt-transport-https
      - ca-certificates
      - zsh
      - vim
      - fonts-powerline
      - fonts-firacode
      - tilix
      - python3
      - transmission
      - steam
      - remmina
      - ffmpeg
      - sqlitebrowser

    snap_package_list:
      - { name: pycharm-community, classic: True }
      - { name: intellij-idea-community, classic: True }

    flatpak_list:
      - { name: us.zoom.Zoom, remote: flathub}
      - { name: org.gnome.meld, remote: flathub}
      - { name: net.bartkessels.getit, remote: flathub }
      - { name: org.libreoffice.LibreOffice, remote: flathub }
      - { name: com.spotify.Client, remote: flathub }
      - { name: com.slack.Slack, remote: flathub }
      - { name: org.openttd.OpenTTD, remote: flathub }
      - { name: org.gnome.Geary, remote: flathub }
      - { name: org.gnome.Boxes, remote: flathub }
      - { name: com.bitwarden.desktop, remote: flathub }

  roles:
    - { name: base_system_tasks, required_packages: "{{ apt_package_list }}" }
    - { name: snap_apps, snap_packages: "{{ snap_package_list }}" }
    - { name: flatpaks, flatpaks: "{{ flatpak_list }}"}
    - postgres
    - gnome_extensions
    - virtualization
    - chrome
    - powershell_core
    - dotnet_core_sdk
    - docker
    - node
    - vscode
