---
- name: Set up a local Ubuntu machine
  connection: local
  hosts: 127.0.0.1
  vars:
    apt_package_list:
      - git
      - geary
      - build-essential
      - cheese
      - curl
      - python3-distutils
      - apt-transport-https
      - ca-certificates
      - postgresql
      - zsh
      - vim
      - fonts-powerline
      - fonts-firacode
      - keepassxc
      - tilix
      - tlp
      - nautilus-dropbox
      - python3
      - python3.7
      - transmission
      - steam
      - remmina
      - ffmpeg

    snap_package_list:
      - { name: bitwarden, classic: False }
      - { name: pycharm-professional, classic: True }
      - { name: sublime-text, classic: True }
      - { name: heroku, classic: True }
      - { name: android-studio, classic: True }
      - { name: intellij-idea-community, classic: True }

    gnome_extensions_list:
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-dashtodock
      - gnome-tweak-tool

    flatpak_list:
      - { name: us.zoom.Zoom, remote: flathub}
      - { name: org.gnome.meld, remote: flathub}
      - { name: net.bartkessels.getit, remote: flathub }
      - { name: org.libreoffice.LibreOffice, remote: flathub }
      - { name: com.spotify.Client, remote: flathub }
      - { name: com.slack.Slack, remote: flathub }
      - { name: org.openttd.OpenTTD, remote: flathub }

  roles:
    - { name: base_system_tasks, apt_packages: "{{ apt_package_list }}" }
    - { name: gnome_extensions, extensions: "{{ gnome_extensions_list }}" }
    - { name: snap_apps, snap_packages: "{{ snap_package_list }}" }
    - { name: flatpaks, flatpaks: "{{ flatpak_list }}"}
    - kvm
    - vscode
    - chrome
    - powershell_core
    - dotnet_core_sdk
    - docker
    - node
