---
rpm_fusion_repos:
  - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
  - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm

postgresql_data_dir: "/var/lib/pgsql/data"

email_packages:
  - thunderbird
  - evolution
  - geary

pgadmin_repo_pubkey_url: "https://www.pgadmin.org/static/packages_pgadmin_org.pub"
pgadmin_repo_url: "deb https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/{{ ansible_distribution_release }} pgadmin4 main"
pgadmin_packages:
  - pgadmin4-desktop
