---
- name: kill elementary appcenter
  command: pkill -f io.elementary.appcenter
  ignore_errors: yes

- name: update and upgrade system packages
  apt:
    update_cache: yes
    upgrade: full
  become: yes

- name: install required packages
  apt:
    name: "{{ apt_packages }}"
    state: latest
    autoremove: yes
  when: apt_packages is defined
  become: yes

- name: remove thunderbird
  apt:
    name: thunderbird
    state: absent
  become: yes

- name: Remove apt libreoffice
  apt:
    name: libreoffice*
    state: absent
    autoremove: yes
    purge: yes

- name: get my zsh theme
  get_url:
    url: "https://raw.githubusercontent.com/Toyonut/zsh-theme/master/paul.zsh-theme"
    dest: ~/.oh-my-zsh/themes/paul.zsh-theme
