---
  - name: add gophers repo
    apt_repository:
      repo: "ppa:gophers/archive"
      state: present

  - name: install Golang {{ go_version }}
    apt:
      package: golang-{{ go_version }}-go
      state: present

  - name: add Go to path
    blockinfile:
      state: present
      path: "{{ vars.shell_rc_path }}"
      block: |
        export PATH=$PATH:/usr/lib/go-1.10/bin
      insertafter: EOF
      marker_begin: GO_BEGIN
      marker_end: GO_END
      backup: yes
    become: no

  - name: set GOPATH
    blockinfile:
      state: present
      path: "{{ vars.shell_rc_path }}"
      block: |
        export GOPATH=$HOME/source/go
      insertafter: EOF
      marker_begin: GOPATH_BEGIN
      marker_end: GOPATH_END
      backup: yes
    become: no
