---
  - name: add gophers repo
    apt_repository:
      repo: "ppa:gophers/archive"
      state: present

  - name: install Golang 10
    apt:
      package: golang-1.10-go
      state: present

  - name: add Go to path
    blockinfile:
      state: present
      path: "{{ vars.shell_rc_path }}"
      block: |
        export PATH=$PATH:/usr/lib/go-1.10/bin
      insertafter: EOF
      marker_begin: GO_BEGIN
      marker_end: GO_END
      backup: yes
    become: no
