---
- name: Ubuntu | Check Snap is installed
  dnf:
    name: snapd
    state: present
  become: yes
  when: ansible_distribution == 'Ubuntu'

- name: Fedora | Check Snap is installed
  yum:
    name: snapd
    state: present
  become: yes
  when: ansible_distribution == 'Fedora'

- name: check Powershell installed
  shell: which pwsh
  register: powershell_installed
  ignore_errors: yes

- name: install Powershell if not installed
  command: snap install powershell --classic
  when: powershell_installed.stdout != '/snap/bin/pwsh'
  become: yes
