---

- name: check if dotnet sdk is installed
  shell: which dotnet
  register: dotnet_installed
  ignore_errors: yes

- include: ubuntu.yml
  when:
    - ansible_distribution in ["Ubuntu", "Pop!_OS", "Linux Mint"]
    - not snap_dotnet_install | bool

- include: fedora.yml
  when:
    - ansible_distribution == 'Fedora'
    - not snap_dotnet_install | bool

- name: install Dotnet sdk from snap
  snap:
    name: "dotnet-sdk"
    classic: yes
  become: yes
  when:
    - snap_dotnet_install | bool
    - dotnet_installed.rc == 1
