---

- name: check if dotnet sdk is installed
  shell: which dotnet
  register: dotnet_installed
  ignore_errors: yes

- include: manual.yml
  when:
    - manual_dotnet_install | bool
    - dotnet_installed.rc == 1

- include: ubuntu.yml
  when:
    - ansible_distribution in ["Ubuntu", "Pop!_OS", "Linux Mint"]
    - not manual_dotnet_install | bool

- include: fedora.yml
  when:
    - ansible_distribution == 'Fedora'
    - not manual_dotnet_install | bool
