---

- stat:
    path: "{{ dotnet_manual_install_directory }}"
  register: dotnet_path

- name: Create dotnet directory if it does not exist
  file:
    path: "{{ dotnet_manual_install_directory }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0751'
  when: not dotnet_path.stat.exists

- name: Download dotnet package with checksum url (sha512)
  get_url:
    url: "{{ dotnet_manual_download_link }}"
    dest: "/tmp/{{ dotnet_binary_package_name }}"
    checksum: sha512:{{ dotnet_package_checksum }}
  when: dotnet_installed.stdout != expected_dotnet_path

- name: unarchive dotnet package
  unarchive:
    src: "/tmp/{{ dotnet_binary_package_name }}"
    dest: "{{ dotnet_manual_install_directory }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    remote_src: yes
  when: dotnet_installed.stdout != expected_dotnet_path

- debug:
    msg: "DOTNET_ROOT is '{{ dotnet_manual_install_directory }}', please add it to your path."
