dotnet_sdk_package:
  - dotnet-sdk-8.0

dotnet_sdk_requirements:
  - apt-transport-https

dotnet_targetting_packs:
  - dotnet-targeting-pack-6.0
  - netstandard-targeting-pack-2.1

dotnet_runtimes:
  - dotnet-runtime-6.0
  - dotnet-runtime-8.0

dotnet_packages: "{{ dotnet_sdk_package + dotnet_sdk_requirements + dotnet_targetting_packs + dotnet_runtimes }}"

# Fedora
fedora_dotnet_baseurl: "https://packages.microsoft.com/fedora/{{ ansible_distribution_version }}/prod/"
fedora_dotnet_key_url: "https://packages.microsoft.com/keys/microsoft.asc"

# Snap package install for if packages aren't available
snap_dotnet_install: no

expected_dotnet_path: "/home/{{ ansible_user_id }}/dotnet/dotnet"
