dotnet_sdk_package: dotnet-sdk-6.0

dotnet_sdk_requirements:
  - apt-transport-https
  - "{{ dotnet_sdk_package }}"

dotnet_targetting_packs:
- aspnetcore-runtime-3.1
- aspnetcore-targeting-pack-3.1
- dotnet-runtime-3.1
- dotnet-targeting-pack-3.1

dotnet_packages: "{{ dotnet_sdk_requirements + dotnet_targetting_packs }}"

# Fedora
fedora_dotnet_baseurl: "https://packages.microsoft.com/fedora/{{ ansible_distribution_version }}/prod/"
fedora_dotnet_key_url: "https://packages.microsoft.com/keys/microsoft.asc"

# Snap package install for if packages aren't available
snap_dotnet_install: no

expected_dotnet_path: "/home/{{ ansible_user_id }}/dotnet/dotnet"
