dotnet_sdk: dotnet-sdk-3.0

dotnet_packages:
  - apt-transport-https
  - "{{ dotnet_sdk }}"

# Fedora
fedora_dotnet_baseurl: "https://packages.microsoft.com/fedora/30/prod/"
fedora_dotnet_key_url: "https://packages.microsoft.com/keys/microsoft.asc"
