---
- name: Install dependencies
  apt:
    name: "{{ dependencies_packages }}"
    state: present
  become: yes

- name: Fetch repo for n
  git:
    repo: 'https://github.com/tj/n.git'
    dest: /home/{{ ansible_user_id }}/tools/n

- name: check n installed
  shell: "which n"
  register: n_installed
  ignore_errors: yes

- name: Install n
  make:
    chdir: /home/{{ ansible_user_id }}/tools/n
    target: install
  when: n_installed.stdout != "/usr/local/bin/n"
  become: yes

- name: Install node with n
  command: "n {{ node_version }}"
  become: yes

- name: Check node installed
  command: "node -v"
  register: node_install

- debug:
    var: node_install.stdout
