---
- name: Check kvm enabled
  command: egrep -c '(vmx|svm)' /proc/cpuinfo
  become: yes
  register: kvm_enabled

- name: Ubuntu | Install KVM pre-requisite packages
  apt:
    name: "{{ kvm_packages }}"
    state: present
  become: yes
  when:
  - kvm_enabled.stdout > "0"
  - ansible_distribution in ["Ubuntu", "Pop!_OS"]

- name: Fedora | Install KVM pre-requisite packages
  dnf:
    name: "{{ kvm_packages }}"
    state: present
  become: yes
  when:
  - kvm_enabled.stdout > "0"
  - ansible_distribution == 'Fedora'

- name: Ensure libvirtd service enabled and started
  systemd:
    name: libvirtd
    state: started
    enabled: yes
    daemon_reload: yes
  become: yes
  when: kvm_enabled.stdout > "0"

- name: Add existing user '{{ ansible_user_id }}' to virt groups Ubuntu
  user:
    name: '{{ ansible_user_id }}'
    groups: "{{ item }}"
    append: yes
  loop: "{{ virt_groups_ubuntu }}"
  become: yes
  when: ansible_distribution in ["Ubuntu", "Pop!_OS"]

- name: Add existing user '{{ ansible_user_id }}' to virt groups Fedora
  user:
    name: '{{ ansible_user_id }}'
    groups: "{{ item }}"
    append: yes
  loop: "{{ virt_groups_fedora }}"
  become: yes
  when: ansible_distribution == 'Fedora'
