---

- include: ubuntu.yml
  when: ansible_distribution in ["Ubuntu", "Pop!_OS"]

- include: fedora.yml
  when: ansible_distribution == 'Fedora'

- name: adding existing user '{{ ansible_user_id }}' to group docker
  user:
    name: '{{ ansible_user_id }}'
    groups: docker
    append: yes
  become: yes

- name: Enable docker service
  systemd:
    name: docker
    enabled: yes
    masked: no
    state: reloaded
  become: yes
