---
- name: Check Snap is installed
  apt:
    name: snapd
    state: present
  become: yes

- name: Install Snap packages
  snap:
    name: "{{ item.name }}"
  when:
    - snap_packages is defined
    - "not item.classic"
  with_items: "{{ snap_packages }}"
  become: yes

- name: Install classic confinement Snap packages
  snap:
    name: "{{ item.name }}"
    classic: yes
  when:
    - snap_packages is defined
    - "item.classic"
  with_items: "{{ snap_packages }}"
  become: yes
