---
- name: Ubuntu | Check Snap is installed
  apt:
    name: snapd
    state: present
  become: yes
  when: ansible_distribution in ['Ubuntu', 'Pop!_OS', 'Linux Mint']

- name: Fedora | Check Snap is installed
  dnf:
    name: snapd
    state: present
  become: yes
  when: ansible_distribution == 'Fedora'

- name: Fedora | Create /snap symlink
  file:
    src: "/var/lib/snapd/snap"
    dest: "/snap"
    owner: root
    group: root
    state: link
  become: yes
  when: ansible_distribution == "Fedora"

- name: Install Snap packages
  snap:
    name: "{{ item.name }}"
  when:
    - snap_packages is defined
    - "not item.classic"
  with_items: "{{ snap_packages }}"
  become: yes

- name: Install classic confinement Snap packages
  snap:
    name: "{{ item.name }}"
    classic: yes
  when:
    - snap_packages is defined
    - "item.classic"
  with_items: "{{ snap_packages }}"
  become: yes

- name: Set Snap update schedule
  command: "snap set system refresh.timer=4:00-7:00,19:00-22:10"
  become: yes
