---
- name: Ubuntu | Check Snap is installed
  apt:
    name: snapd
    state: present
  become: yes
  when: ansible_distribution == 'Ubuntu'

- name: Fedora | Check Snap is installed
  dnf:
    name: snapd
    state: present
  become: yes
  when: ansible_distribution == 'Fedora'

- name: Fedora | Create /snap symlink
  file:
    src: "/var/lib/snapd/snap"
    dest: "/snap"
    owner: root
    group: root
    state: link
  become: yes
  when: ansible_distribution == "Fedora"

- name: Install Snap packages
  snap:
    name: "{{ item.name }}"
  when:
    - snap_packages is defined
    - "not item.classic"
  with_items: "{{ snap_packages }}"
  become: yes

- name: Install classic confinement Snap packages
  snap:
    name: "{{ item.name }}"
    classic: yes
  when:
    - snap_packages is defined
    - "item.classic"
  with_items: "{{ snap_packages }}"
  become: yes

- name: Get Snap location
  command: which snap
  register: snap_location

- name: Set Snap Cron update schedule
  cron:
    name: "Update snaps"
    user: "root"
    special_time: daily
    job: "{{ snap_location.stdout }} refresh"
  become: yes
