---

- name: add pgadmin repo
  yum_repository:
    name: pgadmin
    description: "Pgadmin Repo"
    baseurl: "https://ftp.postgresql.org/pub/pgadmin/pgadmin4/yum/pgadmin4-fedora-repo-2-1.noarch.rpm"
  when: install_pgadmin
  become: yes

- name: add pgadmin to postgres packages
  set_fact:
    postgres_packages_fedora: "{{ postgres_packages_fedora }} + {{ pgagmin_package }}"
  when: install_pgadmin

- name: Install required packages
  dnf:
    name: "{{ postgres_packages_fedora }}"
    state: latest
    update_cache: yes
  become: yes

- name: Check if PostgreSQL database is initialized.
  stat:
    path: "{{ postgresql_data_dir }}/PG_VERSION"
  register: pgdata_dir_version
  become: true

- name: Ensure PostgreSQL database is initialized.
  command: "/usr/bin/postgresql-setup --initdb"
  when: not pgdata_dir_version.stat.exists
  become: true

- name: Enable postgresql service
  systemd:
    name: postgresql
    enabled: yes
    masked: no
    state: reloaded
  become: yes
