---
  - name: get docker gpg key
    get_url:
      url: https://download.docker.com/linux/ubuntu/gpg
      dest: /tmp/docker_gpg
  
  - name: install docker gpg key
    command: apt-key add /tmp/docker_gpg
  
  - name: add docker repo
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ vars.release }} stable"
      state: present
  
  - name: install required packages
    apt: 
      name: "{{ packages }}"
      state: latest
      update_cache: yes
    vars:
      packages: 
        - docker-ce 
        - docker-compose
  
  - name: adding existing user '{{ vars.user }}' to group docker
    user:
      name: '{{ vars.user }}'
      groups: docker
      append: yes
