---

- name: Install Flathub ppa
  apt_repository:
    repo: ppa:alexlarsson/flatpak
    state: present
    update_cache: yes
  when:
    - flatpak_install_ppa
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version < "18.10"
  become: yes
  register: flatpak_repo_installed

- name: Install Flatpak pre-reqs
  apt:
    name: "{{ flatpak_pre_req_packages }}"
    update-cache: Yes
    state: present
  become: yes
  when:
    - ansible_distribution == 'Ubuntu'
    - flatpak_repo_installed.changed
  register: flatpak_installed

- name: Add Flatpak remote
  flatpak_remote:
    name: "{{ item.name }}"
    flatpakrepo_url: "{{ item.remote_url }}"
  with_items: "{{ flatpak_repos }}"
  become: yes

- name: Install Flatpak apps
  flatpak:
    name: "{{ item.name }}"
    remote: "{{ item.remote }}"
  with_items: "{{ flatpaks }}"
  become: yes

- name: Get Flatpak location
  command: which flatpak
  when: flatpak_installed.changed
  register: flatpak_location

- name: Set Flatpak Cron update schedule
  cron:
    name: "Update Flatpaks"
    user: "root"
    special_time: daily
    job: "{{ flatpak_location.stdout }} update -y"
  when: flatpak_installed.changed
  become: yes

