---

- name: Install Flathub ppa
  apt_repository:
    repo: ppa:alexlarsson/flatpak
    state: present
    update_cache: yes
  when:
    - flatpak_install_ppa
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version < "18.10"
  become: yes
  register: flatpak_repo_installed

- name: Install Flatpak pre-reqs
  apt:
    name: "{{ flatpak_pre_req_packages }}"
    update-cache: Yes
    state: present
  become: yes
  when:
    - ansible_distribution == 'Ubuntu'
    - flatpak_repo_installed.changed
  register: flatpak_installed

- name: Add Flatpak remote
  flatpak_remote:
    name: "{{ item.name }}"
    flatpakrepo_url: "{{ item.remote_url }}"
  with_items: "{{ flatpak_repos }}"
  become: yes

- name: Install Flatpak apps
  flatpak:
    name: "{{ item.name }}"
    remote: "{{ item.remote }}"
  with_items: "{{ flatpaks }}"
  become: yes

- name: Add Flatpak update systemd timer
  blockinfile:
    path: /etc/systemd/system/flatpak-update.timer
    create: yes
    block: |
      [Unit]
      Description=Flatpak update

      [Timer]
      OnCalendar=20:00
      Persistent=true

      [Install]
      WantedBy=timers.target
  become: yes
  when: flatpak_installed.changed

- name: Add Flatpak update systemd unit file
  blockinfile:
    path: /etc/systemd/system/flatpak-update.service
    create: yes
    block: |
      [Unit]
      Description=Flatpak update

      [Service]
      Type=oneshot
      ExecStart=/usr/bin/flatpak update -y
  become: yes
  when: flatpak_installed.changed

- name: Set up Flatpak auto update systemd
  systemd:
    name: flatpak-update.timer
    enabled: yes
    state: started
    daemon_reload: yes
  become: yes
  when: flatpak_installed.changed
